version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Running tests...
      - cat package.json
artifacts:
  files:
    - appspec.yml
    - scripts/**/*       # ✅ include all deployment scripts
    - app.js
    - package.json
    - node_modules/**/*
